
export const SET_FRETBOARD = "SET_FRETBOARD";
export const SET_FRETBOARDS  = "SET_FRETBOARDS";

export const TOGGLE_NOTE = "TOGGLE_NOTE";
export const DISPLAY_NOTE = "DISPLAY_NOTE";

export const SET_KEY = "SET_KEY";

export const SET_SCALE = "SET_SCALE";
export const SET_SCALE_FORMULA = "SET_SCALE_FORMULA";
export const SET_SCALE_NOTES = "SET_SCALE_NOTES";
export const SET_SCALE_INTERVALS = "SET_SCALE_INTERVALS";

export const SET_MODE = "SET_MODE";
export const SET_MODE_NOTES = "SET_MODE_NOTES";
export const SET_MODE_INTERVALS = "SET_MODE_INTERVALS";

export const SET_ARPPEGIO = "SET_ARPPEGIO";
export const SET_ARPPEGIO_NOTES = "SET_ARPPEGIO_NOTES";
export const SET_ARPPEGIO_INTERVALS = "SET_ARPPEGIO_INTERVALS";

export const SET_CHORD = "SET_CHORD";

export const SET_FRET = "SET_FRET";

export const SET_NOTES_DISPLAY = "SET_NOTES_DISPLAY";

export const SET_CIRCLE_OF_FIFTHS_ROTATION = "SET_CIRCLE_OF_FIFTHS_ROTATION";

export const SET_DASHED_CIRCLE_ROTATION = "SET_DASHED_CIRCLE_ROTATION";

export const SET_SHAPE = "SET_SHAPE";
export const SET_CHORD_PROGRESSION = "SET_CHORD_PROGRESSION";

export const UPDATE_FRETBOARD_PROPERTY = 'UPDATE_FRETBOARD_PROPERTY';

