
export const FILL_FRETBOARD = "FILL_FRETBOARD";

export const TOGGLE_NOTE = "TOGGLE_NOTE";
export const DISPLAY_NOTE = "DISPLAY_NOTE";

export const SET_KEY = "SET_KEY";

export const SET_SCALE = "SET_SCALE";
export const SET_SCALE_FORMULA = "SET_SCALE_FORMULA";
export const SET_SCALE_NOTES = "SET_SCALE_NOTES";
export const SET_SCALE_INTERVALS = "SET_SCALE_INTERVALS";

export const SET_MODE = "SET_MODE";
export const SET_MODE_NOTES = "SET_MODE_NOTES";
export const SET_MODE_INTERVALS = "SET_MODE_INTERVALS";

export const SET_ARPPEGIO = "SET_ARPPEGIO";
export const SET_ARPPEGIO_NOTES = "SET_ARPPEGIO_NOTES";
export const SET_ARPPEGIO_INTERVALS = "SET_ARPPEGIO_INTERVALS";

export const SET_CHORD = "SET_CHORD";

export const SET_POSITION = "SET_POSITION";

export const SET_IS_NOTES_DISPLAY = "SET_IS_NOTES_DISPLAY";